# Generated by Django 5.0.4 on 2024-04-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cor_marca_tamanho_alter_categoria_imagem_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(upload_to='categoria_img/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='imagem',
            field=models.ImageField(upload_to='marca_img/'),
        ),
    ]
