# Generated by Django 5.0.4 on 2024-04-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_banner_remove_produto_preco_produtoatributo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_feat',
            field=models.BooleanField(default=False),
        ),
    ]
